/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ArticleStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Category = IDL.Variant({
  'AFR' : IDL.Null,
  'EnergyOptimization' : IDL.Null,
  'Kiln' : IDL.Null,
  'CementMill' : IDL.Null,
  'RawMill' : IDL.Null,
});
export const CreateArticleInput = IDL.Record({
  'metaDescription' : IDL.Text,
  'status' : ArticleStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : Timestamp,
  'slug' : IDL.Text,
  'authorName' : IDL.Text,
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Text,
  'category' : Category,
});
export const ArticleId = IDL.Nat;
export const Article = IDL.Record({
  'id' : ArticleId,
  'metaDescription' : IDL.Text,
  'status' : ArticleStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : Timestamp,
  'slug' : IDL.Text,
  'authorName' : IDL.Text,
  'lastUpdated' : Timestamp,
  'viewCount' : IDL.Nat,
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Text,
  'category' : Category,
});
export const SortBy = IDL.Variant({
  'date' : IDL.Null,
  'viewCount' : IDL.Null,
});
export const ListArticlesFilter = IDL.Record({
  'status' : IDL.Opt(ArticleStatus),
  'sortBy' : SortBy,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'category' : IDL.Opt(Category),
});
export const ArticleListResult = IDL.Record({
  'total' : IDL.Nat,
  'articles' : IDL.Vec(Article),
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
});
export const UpdateArticleInput = IDL.Record({
  'id' : ArticleId,
  'metaDescription' : IDL.Text,
  'status' : ArticleStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : Timestamp,
  'slug' : IDL.Text,
  'authorName' : IDL.Text,
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Text,
  'category' : Category,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'adminVerifyToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArticle' : IDL.Func(
      [IDL.Opt(IDL.Text), CreateArticleInput],
      [ArticleId],
      [],
    ),
  'deleteArticle' : IDL.Func([IDL.Opt(IDL.Text), ArticleId], [], []),
  'getArticle' : IDL.Func([ArticleId], [IDL.Opt(Article)], ['query']),
  'getArticleBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Article)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLatestArticles' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
  'getPopularArticles' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
  'incrementViewCount' : IDL.Func([ArticleId], [], []),
  'isAdmin' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listArticles' : IDL.Func(
      [ListArticlesFilter],
      [ArticleListResult],
      ['query'],
    ),
  'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'updateArticle' : IDL.Func([IDL.Opt(IDL.Text), UpdateArticleInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ArticleStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Category = IDL.Variant({
    'AFR' : IDL.Null,
    'EnergyOptimization' : IDL.Null,
    'Kiln' : IDL.Null,
    'CementMill' : IDL.Null,
    'RawMill' : IDL.Null,
  });
  const CreateArticleInput = IDL.Record({
    'metaDescription' : IDL.Text,
    'status' : ArticleStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : Timestamp,
    'slug' : IDL.Text,
    'authorName' : IDL.Text,
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Text,
    'category' : Category,
  });
  const ArticleId = IDL.Nat;
  const Article = IDL.Record({
    'id' : ArticleId,
    'metaDescription' : IDL.Text,
    'status' : ArticleStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : Timestamp,
    'slug' : IDL.Text,
    'authorName' : IDL.Text,
    'lastUpdated' : Timestamp,
    'viewCount' : IDL.Nat,
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Text,
    'category' : Category,
  });
  const SortBy = IDL.Variant({ 'date' : IDL.Null, 'viewCount' : IDL.Null });
  const ListArticlesFilter = IDL.Record({
    'status' : IDL.Opt(ArticleStatus),
    'sortBy' : SortBy,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'category' : IDL.Opt(Category),
  });
  const ArticleListResult = IDL.Record({
    'total' : IDL.Nat,
    'articles' : IDL.Vec(Article),
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
  });
  const UpdateArticleInput = IDL.Record({
    'id' : ArticleId,
    'metaDescription' : IDL.Text,
    'status' : ArticleStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : Timestamp,
    'slug' : IDL.Text,
    'authorName' : IDL.Text,
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Text,
    'category' : Category,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'adminVerifyToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArticle' : IDL.Func(
        [IDL.Opt(IDL.Text), CreateArticleInput],
        [ArticleId],
        [],
      ),
    'deleteArticle' : IDL.Func([IDL.Opt(IDL.Text), ArticleId], [], []),
    'getArticle' : IDL.Func([ArticleId], [IDL.Opt(Article)], ['query']),
    'getArticleBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Article)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLatestArticles' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
    'getPopularArticles' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
    'incrementViewCount' : IDL.Func([ArticleId], [], []),
    'isAdmin' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listArticles' : IDL.Func(
        [ListArticlesFilter],
        [ArticleListResult],
        ['query'],
      ),
    'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
    'updateArticle' : IDL.Func([IDL.Opt(IDL.Text), UpdateArticleInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };