/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : ArticleId,
  'metaDescription' : string,
  'status' : ArticleStatus,
  'title' : string,
  'content' : string,
  'publishDate' : Timestamp,
  'slug' : string,
  'authorName' : string,
  'lastUpdated' : Timestamp,
  'viewCount' : bigint,
  'featuredImageUrl' : [] | [string],
  'excerpt' : string,
  'category' : Category,
}
export type ArticleId = bigint;
export interface ArticleListResult {
  'total' : bigint,
  'articles' : Array<Article>,
  'page' : bigint,
  'pageSize' : bigint,
}
export type ArticleStatus = { 'published' : null } |
  { 'draft' : null };
export type Category = { 'AFR' : null } |
  { 'EnergyOptimization' : null } |
  { 'Kiln' : null } |
  { 'CementMill' : null } |
  { 'RawMill' : null };
export interface CreateArticleInput {
  'metaDescription' : string,
  'status' : ArticleStatus,
  'title' : string,
  'content' : string,
  'publishDate' : Timestamp,
  'slug' : string,
  'authorName' : string,
  'featuredImageUrl' : [] | [string],
  'excerpt' : string,
  'category' : Category,
}
export interface ListArticlesFilter {
  'status' : [] | [ArticleStatus],
  'sortBy' : SortBy,
  'page' : bigint,
  'pageSize' : bigint,
  'category' : [] | [Category],
}
export type SortBy = { 'date' : null } |
  { 'viewCount' : null };
export type Timestamp = bigint;
export interface UpdateArticleInput {
  'id' : ArticleId,
  'metaDescription' : string,
  'status' : ArticleStatus,
  'title' : string,
  'content' : string,
  'publishDate' : Timestamp,
  'slug' : string,
  'authorName' : string,
  'featuredImageUrl' : [] | [string],
  'excerpt' : string,
  'category' : Category,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adminLogin' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminLogout' : ActorMethod<[string], undefined>,
  'adminVerifyToken' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArticle' : ActorMethod<[[] | [string], CreateArticleInput], ArticleId>,
  'deleteArticle' : ActorMethod<[[] | [string], ArticleId], undefined>,
  'getArticle' : ActorMethod<[ArticleId], [] | [Article]>,
  'getArticleBySlug' : ActorMethod<[string], [] | [Article]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLatestArticles' : ActorMethod<[bigint], Array<Article>>,
  'getPopularArticles' : ActorMethod<[bigint], Array<Article>>,
  'incrementViewCount' : ActorMethod<[ArticleId], undefined>,
  'isAdmin' : ActorMethod<[[] | [string]], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listArticles' : ActorMethod<[ListArticlesFilter], ArticleListResult>,
  'searchArticles' : ActorMethod<[string], Array<Article>>,
  'updateArticle' : ActorMethod<[[] | [string], UpdateArticleInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];