/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ListArticlesFilter {
    status?: ArticleStatus;
    sortBy: SortBy;
    page: bigint;
    pageSize: bigint;
    category?: Category;
}
export type ArticleId = bigint;
export interface CreateArticleInput {
    metaDescription: string;
    status: ArticleStatus;
    title: string;
    content: string;
    publishDate: Timestamp;
    slug: string;
    authorName: string;
    featuredImageUrl?: string;
    excerpt: string;
    category: Category;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UpdateArticleInput {
    id: ArticleId;
    metaDescription: string;
    status: ArticleStatus;
    title: string;
    content: string;
    publishDate: Timestamp;
    slug: string;
    authorName: string;
    featuredImageUrl?: string;
    excerpt: string;
    category: Category;
}
export interface ArticleListResult {
    total: bigint;
    articles: Array<Article>;
    page: bigint;
    pageSize: bigint;
}
export interface Article {
    id: ArticleId;
    metaDescription: string;
    status: ArticleStatus;
    title: string;
    content: string;
    publishDate: Timestamp;
    slug: string;
    authorName: string;
    lastUpdated: Timestamp;
    viewCount: bigint;
    featuredImageUrl?: string;
    excerpt: string;
    category: Category;
}
export enum ArticleStatus {
    published = "published",
    draft = "draft"
}
export enum Category {
    AFR = "AFR",
    EnergyOptimization = "EnergyOptimization",
    Kiln = "Kiln",
    CementMill = "CementMill",
    RawMill = "RawMill"
}
export enum SortBy {
    date = "date",
    viewCount = "viewCount"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    adminLogin(username: string, passwordHash: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminLogout(token: string): Promise<void>;
    adminVerifyToken(token: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createArticle(token: string | null, input: CreateArticleInput): Promise<ArticleId>;
    deleteArticle(token: string | null, id: ArticleId): Promise<void>;
    getArticle(id: ArticleId): Promise<Article | null>;
    getArticleBySlug(slug: string): Promise<Article | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLatestArticles(n: bigint): Promise<Array<Article>>;
    getPopularArticles(n: bigint): Promise<Array<Article>>;
    incrementViewCount(id: ArticleId): Promise<void>;
    isAdmin(token: string | null): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listArticles(filter: ListArticlesFilter): Promise<ArticleListResult>;
    searchArticles(searchTerm: string): Promise<Array<Article>>;
    updateArticle(token: string | null, input: UpdateArticleInput): Promise<void>;
}
import type { Article as _Article, ArticleId as _ArticleId, ArticleListResult as _ArticleListResult, ArticleStatus as _ArticleStatus, Category as _Category, CreateArticleInput as _CreateArticleInput, ListArticlesFilter as _ListArticlesFilter, SortBy as _SortBy, Timestamp as _Timestamp, UpdateArticleInput as _UpdateArticleInput, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout(arg0);
            return result;
        }
    }
    async adminVerifyToken(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminVerifyToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminVerifyToken(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createArticle(arg0: string | null, arg1: CreateArticleInput): Promise<ArticleId> {
        if (this.processError) {
            try {
                const result = await this.actor.createArticle(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), to_candid_CreateArticleInput_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArticle(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), to_candid_CreateArticleInput_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteArticle(arg0: string | null, arg1: ArticleId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArticle(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArticle(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async getArticle(arg0: ArticleId): Promise<Article | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticle(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticle(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticleBySlug(arg0: string): Promise<Article | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticleBySlug(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticleBySlug(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestArticles(arg0: bigint): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestArticles(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestArticles(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPopularArticles(arg0: bigint): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPopularArticles(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPopularArticles(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementViewCount(arg0: ArticleId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementViewCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementViewCount(arg0);
            return result;
        }
    }
    async isAdmin(arg0: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listArticles(arg0: ListArticlesFilter): Promise<ArticleListResult> {
        if (this.processError) {
            try {
                const result = await this.actor.listArticles(to_candid_ListArticlesFilter_n29(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ArticleListResult_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listArticles(to_candid_ListArticlesFilter_n29(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ArticleListResult_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchArticles(arg0: string): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchArticles(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchArticles(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateArticle(arg0: string | null, arg1: UpdateArticleInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArticle(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), to_candid_UpdateArticleInput_n35(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArticle(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), to_candid_UpdateArticleInput_n35(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ArticleListResult_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArticleListResult): ArticleListResult {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_ArticleStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArticleStatus): ArticleStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Article_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Article): Article {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Article]): Article | null {
    return value.length === 0 ? null : from_candid_Article_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ArticleId;
    metaDescription: string;
    status: _ArticleStatus;
    title: string;
    content: string;
    publishDate: _Timestamp;
    slug: string;
    authorName: string;
    lastUpdated: _Timestamp;
    viewCount: bigint;
    featuredImageUrl: [] | [string];
    excerpt: string;
    category: _Category;
}): {
    id: ArticleId;
    metaDescription: string;
    status: ArticleStatus;
    title: string;
    content: string;
    publishDate: Timestamp;
    slug: string;
    authorName: string;
    lastUpdated: Timestamp;
    viewCount: bigint;
    featuredImageUrl?: string;
    excerpt: string;
    category: Category;
} {
    return {
        id: value.id,
        metaDescription: value.metaDescription,
        status: from_candid_ArticleStatus_n21(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        publishDate: value.publishDate,
        slug: value.slug,
        authorName: value.authorName,
        lastUpdated: value.lastUpdated,
        viewCount: value.viewCount,
        featuredImageUrl: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.featuredImageUrl)),
        excerpt: value.excerpt,
        category: from_candid_Category_n24(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    articles: Array<_Article>;
    page: bigint;
    pageSize: bigint;
}): {
    total: bigint;
    articles: Array<Article>;
    page: bigint;
    pageSize: bigint;
} {
    return {
        total: value.total,
        articles: from_candid_vec_n28(_uploadFile, _downloadFile, value.articles),
        page: value.page,
        pageSize: value.pageSize
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    draft: null;
}): ArticleStatus {
    return "published" in value ? ArticleStatus.published : "draft" in value ? ArticleStatus.draft : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    AFR: null;
} | {
    EnergyOptimization: null;
} | {
    Kiln: null;
} | {
    CementMill: null;
} | {
    RawMill: null;
}): Category {
    return "AFR" in value ? Category.AFR : "EnergyOptimization" in value ? Category.EnergyOptimization : "Kiln" in value ? Category.Kiln : "CementMill" in value ? Category.CementMill : "RawMill" in value ? Category.RawMill : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Article>): Array<Article> {
    return value.map((x)=>from_candid_Article_n19(_uploadFile, _downloadFile, x));
}
function to_candid_ArticleStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleStatus): _ArticleStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_CreateArticleInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateArticleInput): _CreateArticleInput {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ListArticlesFilter_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListArticlesFilter): _ListArticlesFilter {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_SortBy_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy): _SortBy {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateArticleInput_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateArticleInput): _UpdateArticleInput {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metaDescription: string;
    status: ArticleStatus;
    title: string;
    content: string;
    publishDate: Timestamp;
    slug: string;
    authorName: string;
    featuredImageUrl?: string;
    excerpt: string;
    category: Category;
}): {
    metaDescription: string;
    status: _ArticleStatus;
    title: string;
    content: string;
    publishDate: _Timestamp;
    slug: string;
    authorName: string;
    featuredImageUrl: [] | [string];
    excerpt: string;
    category: _Category;
} {
    return {
        metaDescription: value.metaDescription,
        status: to_candid_ArticleStatus_n14(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        publishDate: value.publishDate,
        slug: value.slug,
        authorName: value.authorName,
        featuredImageUrl: value.featuredImageUrl ? candid_some(value.featuredImageUrl) : candid_none(),
        excerpt: value.excerpt,
        category: to_candid_Category_n16(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: ArticleStatus;
    sortBy: SortBy;
    page: bigint;
    pageSize: bigint;
    category?: Category;
}): {
    status: [] | [_ArticleStatus];
    sortBy: _SortBy;
    page: bigint;
    pageSize: bigint;
    category: [] | [_Category];
} {
    return {
        status: value.status ? candid_some(to_candid_ArticleStatus_n14(_uploadFile, _downloadFile, value.status)) : candid_none(),
        sortBy: to_candid_SortBy_n31(_uploadFile, _downloadFile, value.sortBy),
        page: value.page,
        pageSize: value.pageSize,
        category: value.category ? candid_some(to_candid_Category_n16(_uploadFile, _downloadFile, value.category)) : candid_none()
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ArticleId;
    metaDescription: string;
    status: ArticleStatus;
    title: string;
    content: string;
    publishDate: Timestamp;
    slug: string;
    authorName: string;
    featuredImageUrl?: string;
    excerpt: string;
    category: Category;
}): {
    id: _ArticleId;
    metaDescription: string;
    status: _ArticleStatus;
    title: string;
    content: string;
    publishDate: _Timestamp;
    slug: string;
    authorName: string;
    featuredImageUrl: [] | [string];
    excerpt: string;
    category: _Category;
} {
    return {
        id: value.id,
        metaDescription: value.metaDescription,
        status: to_candid_ArticleStatus_n14(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        publishDate: value.publishDate,
        slug: value.slug,
        authorName: value.authorName,
        featuredImageUrl: value.featuredImageUrl ? candid_some(value.featuredImageUrl) : candid_none(),
        excerpt: value.excerpt,
        category: to_candid_Category_n16(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleStatus): {
    published: null;
} | {
    draft: null;
} {
    return value == ArticleStatus.published ? {
        published: null
    } : value == ArticleStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    AFR: null;
} | {
    EnergyOptimization: null;
} | {
    Kiln: null;
} | {
    CementMill: null;
} | {
    RawMill: null;
} {
    return value == Category.AFR ? {
        AFR: null
    } : value == Category.EnergyOptimization ? {
        EnergyOptimization: null
    } : value == Category.Kiln ? {
        Kiln: null
    } : value == Category.CementMill ? {
        CementMill: null
    } : value == Category.RawMill ? {
        RawMill: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy): {
    date: null;
} | {
    viewCount: null;
} {
    return value == SortBy.date ? {
        date: null
    } : value == SortBy.viewCount ? {
        viewCount: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
